In [1]:
import data.utils as d_utils
import torchvision.transforms as transforms
import torch.utils.data as data
import numpy as np

frame_trans = transforms.Compose([transforms.Resize([256, 256]),
                                      transforms.Grayscale(num_output_channels=1),
                                      transforms.ToTensor(),
                                      transforms.Normalize([0.5], [0.5])])
label_orig = np.load('./ckpt/UCSDped1_gt.npy', allow_pickle=True)
for label in label_orig:
    print('frame size:', len(label))
    print(label)
t_train = d_utils.DataLoader('./data/UCSDped1/Train_jpg/', frame_trans, None, True, time_step=15, num_pred=1, video_start=1, video_end=5)
print(len(t_train))
t_test = d_utils.DataLoader('./data/UCSDped1/Test_jpg/', frame_trans, label_orig, False, time_step=15, num_pred=1, video_start=1, video_end=5)
print(len(t_test))
t_train = data.ConcatDataset([t_train, t_test])
print(len(t_train))
# data = dataset.__getitem__(0)
# print(img)
# print(img.size())
# print(dataset.videos['Train001'])
# batch = data.DataLoader(dataset, batch_size=1, shuffle=False, num_workers=0, drop_last=True)
# i = 0
# for frames, label in batch:
#     print(label)
#     if label == label_orig[0][i+8]:
#         print('same')
#     else:
#         print('different')
#     i += 1
#     if i == 191:
#         break

frame size: 200
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
frame size: 200
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
frame size: 200
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [2]:
import numpy as np
label_orig = np.load('./ckpt/UCSDped1_gt.npy', allow_pickle=True)
print(len(label_orig))
print(type(label_orig))
print(label_orig)
for video in range(len(label_orig)):
    print(len(label_orig[video]))

36
<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]]
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200


In [3]:
score_orig = np.load('./ckpt/UCSDped2/recons_error_original_1.0_40.npy', allow_pickle=True)
print(type(score_orig))
print(score_orig.shape)
# for a in arr:
#     print(a)

<class 'numpy.ndarray'>
(1830,)
